resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/jfernandezrico/testconcourse
    branch: master
- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{repo-username}}
    password: {{repo-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml
    params:
      M2_SETTINGS_REPO_ID : {{repo-id}}
      M2_SETTINGS_REPO_USERNAME : {{repo-username}}
      M2_SETTINGS_REPO_PASSWORD : {{repo-password}}
      M2_SETTINGS_REPO_RELEASE_URI : {{repo-release-uri}}
      M2_SETTINGS_REPO_SNAPSHOT_URI : {{repo-snapshot-uri}}
- put: resource-deploy-web-app
  params:
    manifest: source-code/manifest.yml
    path: output-code/*.jar