resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: messages
  type: git
  source:
    uri: https://github.com/MarcialRosales/maven-concourse-pipeline
- name: source-code
  type: git
  source:
    uri: https://github.com/jfernandezrico/testconcourse
    branch: master
- name: slack-greeeting
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
- name: every1m
  type: time
  source: {interval: 1m}
    

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/tasks/build.yml
    params:
      M2_SETTINGS_REPO_ID : {{repo-id}}
      M2_SETTINGS_REPO_USERNAME : {{repo-username}}
      M2_SETTINGS_REPO_PASSWORD : {{repo-password}}
      M2_SETTINGS_REPO_RELEASE_URI : {{repo-release-uri}}
      M2_SETTINGS_REPO_SNAPSHOT_URI : {{repo-snapshot-uri}}
    
- name: job-hello-world
  plan:
  - get: messages
    trigger: true
  - get: every1m
    trigger: true
  - task: produce-greeting
    on_failure:
      put: slack-greeeting
      params:
        text_file: greetings/greeting
        text: |
          The task print-greeting has failed. Check it out at: $ATC_EXTERNAL_URL/builds/$BUILD_ID
          Result was: $TEXT_FILE_CONTENT
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: messages
      outputs:
        - name: greetings
      run:
        path: sh
        args:
          - -c
          - |
            MSG=`head -1 messages/README.md`
            echo "hello $MSG !!!" > greeting
            cp greeting greetings
  - task: print-greeting
    config:
            platform: linux
            image_resource:
                    type: docker-image
                    source:
                            repository: busybox
            inputs:
                    - name: greetings
            run:
                    path: sh
                    args:
                            - -c
                            - |
                              cat greetings/greeting
